### PR TITLE
Added Connecton and Updated Make_Tables

### LINKED ISSUE #19: Connect flask app to mysql db
Get the env variables and connect to mysql db

### PR DESCRIPTION
**Pull request by Signior-X**
I have added the database connection to the flask by importing a file know as mysqlconnect.py
If anyone needs a connection just they need to import mydb from this file, and can execute statements.
I have also added a file in Make_Tables, by that other contributors can easily copy code from it to insert or see the tables as many of them don't know the schema of the tables still.
Also Suggestion expected.

### CODE REVIEW

**Comment by Signior-X** [comment]
I have done some mistakes, so corrected it

**Review by Milind712000 — CHANGES_REQUESTED** [review]
- [ ] is the empty init.py nescessary, if not remove it
- [x] undo the changes made to the login route, there are things like hashing and starting a session which need to be done for it so it'll be better if they are done together
- [ ] instead of running 'use sac_data' everywhere can we run it once in msqlconnect.py before exporting it

**Comment by Signior-X** [comment]
__init__.py is necessary it defines that the Make_Tables folder is a python folder
okay, i was thinking that I am removing them.
okay, trying to get it done in the mysqlconnect.py file

**Comment by Signior-X** [comment]
Did what you suggested, check them
Also, in the flask app, anyone can execute the statements using the mycursor and mydb, or if he wants, he can create the insert statements using the  create_insert_statement function.

**Comment by Milind712000** [comment]
According to this empty __inti__.py are redundant
https://stackoverflow.com/questions/37139786/is-init-py-not-required-for-packages-in-python-3-3

**Comment by Signior-X** [comment]
Yes, I read it, __init__.py is not needed. Done. Check it if any other change is needed.

**Review by Milind712000 — APPROVED** [review]

**Pull request merged**
